# Generated by Django 2.2.2 on 2019-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, choices=[(0, 'Hobbit'), (1, 'Lord of the ring'), (2, 'paid')], default='', max_length=36, null=True, unique=True),
        ),
    ]
