# Generated by Django 2.2.2 on 2019-06-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190613_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(default='', max_length=36),
            preserve_default=False,
        ),
    ]
